# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-19 00:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_migrate_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='description',
            field=models.TextField(help_text='Please briefly describe this data source.', verbose_name='Data Source Description'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='ehb_service_es_id',
            field=models.IntegerField(default=-1, editable=False, verbose_name='EHB Service External System ID'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Data Source Name'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='url',
            field=models.URLField(max_length=255, unique=True, verbose_name='Data Source URL'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subject_id_label',
            field=models.CharField(default='Record ID', max_length=50, verbose_name='Unique Subject Record ID Label'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Protocol Name'),
        ),
        migrations.AlterField(
            model_name='protocoldatasource',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DataSource', verbose_name='Data Source'),
        ),
        migrations.AlterField(
            model_name='protocoldatasource',
            name='display_label',
            field=models.CharField(max_length=50, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='protocoldatasource',
            name='driver',
            field=models.IntegerField(choices=[(0, 'REDCap Client'), (1, 'Nautilus'), (2, 'Phenotype Intake'), (3, 'External Identifiers')], verbose_name='Driver Name'),
        ),
        migrations.AlterField(
            model_name='protocoldatasource',
            name='driver_configuration',
            field=models.TextField(blank=True, verbose_name='Driver Configuration Options'),
        ),
        migrations.AlterField(
            model_name='protocoldatasource',
            name='max_records_per_subject',
            field=models.IntegerField(default=-1, verbose_name='Maximum Number of Records Allowed Per Subject'),
        ),
        migrations.AlterField(
            model_name='protocoldatasource',
            name='path',
            field=models.CharField(max_length=255, verbose_name='Path to record collection'),
        ),
        migrations.AlterField(
            model_name='protocoldatasourcelink',
            name='linker',
            field=models.CharField(max_length=200, verbose_name='Linking Plugin'),
        ),
        migrations.AlterField(
            model_name='protocoldatasourcelink',
            name='pds_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pds_one_set', to='api.ProtocolDataSource', verbose_name='Protocol Data Source'),
        ),
        migrations.AlterField(
            model_name='protocoldatasourcelink',
            name='pds_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pds_two_set', to='api.ProtocolDataSource', verbose_name='Protocol Data Source'),
        ),
        migrations.AlterField(
            model_name='protocoluser',
            name='role',
            field=models.IntegerField(choices=[(0, 'Research Coordinator')]),
        ),
        migrations.AlterField(
            model_name='protocolusercredentials',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProtocolDataSource', verbose_name='Protocol Data Source'),
        ),
        migrations.AlterField(
            model_name='protocolusercredentials',
            name='data_source_password',
            field=models.CharField(max_length=128, verbose_name='Password for Data Source'),
        ),
        migrations.AlterField(
            model_name='protocolusercredentials',
            name='data_source_username',
            field=models.CharField(blank=True, max_length=50, verbose_name='Username for Data Source'),
        ),
        migrations.AlterField(
            model_name='protocolusercredentials',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Protocol', verbose_name='Protocol'),
        ),
        migrations.AlterField(
            model_name='protocolusercredentials',
            name='protocol_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProtocolUser', verbose_name='Protocol User'),
        ),
        migrations.AlterField(
            model_name='protocolusercredentials',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
