# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-22 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_password_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='institutional_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
